### ISSUE TITLE
No dark mode styles available

### ISSUE THREAD

**Issue by christian-bromann** [saucelabs/sauce-docs#227]
### Have you read the [Contributing Guidelines on issues?](https://github.com/saucelabs/sauce-docs/blob/master/CONTRIBUTING.MD#reporting-bugs)

- [x] Yes

## Description

I am using MacOS and enabled dark mode on a system level. This propagates into the browser and makes Docusarus automatically use dark mode too. However the Sauce specific styles don't have a dark mode version yet (it seems only on the front page and header) making the site look like this:

![Screenshot 2021-03-04 at 16 28 11](https://user-images.githubusercontent.com/731337/109988043-6ce32280-7d07-11eb-95a2-db65f91cf53e.png)

![Screenshot 2021-03-04 at 16 35 44](https://user-images.githubusercontent.com/731337/109988302-b16ebe00-7d07-11eb-8dfb-8d045e58d430.png)

## To Reproduce

Switch do dark mode in your system and open the app.

## Expected Behavior

I suggest to have some Sauce specific Dark Mode styles 🌕 🕶

## Actual Behavior

A mix of both

## Your Environment

* OS: OSX
* Node version:
* Docusaurus version:
* Browser version:

**Comment by sweeneyskirt-sl** [comment]
Hi @christian-bromann! James turned on the dark-mode option for the docs, so we now have a selection toggle that applies the dark mode theme. 
![Screen Shot 2021-05-14 at 1 46 01 PM](https://user-images.githubusercontent.com/70522750/118309342-1fc7bd80-b4bb-11eb-9001-1d313b3a5e9c.png)
![Screen Shot 2021-05-14 at 1 47 14 PM](https://user-images.githubusercontent.com/70522750/118309348-22c2ae00-b4bb-11eb-8245-e2ddca10a1c1.png)
I believe it defaults to whichever system setting you have set, but you can also override the system setting as desired. Does this adequately solve your issue? Thanks!

**Comment by guinaut** [comment]
Hi.  We're very happy to announce that we've added Dark Mode.  If we missed anything, please let us know.

Thanks,

Matt Wyman

Chief Product & Growth Officer, SauceLabs
