### ISSUE TITLE
Incorrect package in Storybook integration guide

### ISSUE THREAD

**Issue by zachwolf** [saucelabs/sauce-docs#2975]
### Have you read the [Contributing Guidelines on issues?](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md#reporting-bugs)

- [X] Yes

## Description

__Doc URL:__  [Storybook Integration (Deployed)](https://docs.saucelabs.com/visual-testing/integrations/storybook/index.html) and [markdown](https://github.com/saucelabs/sauce-docs/blob/main/docs/visual-testing/integrations/storybook.md)

While following the getting started guide, suggested command `npx test-storybook --eject` fails with `could not determine executable to run`. I believe this command is incorrect

[test-storybook](https://www.npmjs.com/package/test-storybook) is a package that hasn't been updated in ~7 years

Getting Started Step 1 links to [Storybook's instructions](https://github.com/storybookjs/test-runner/blob/next/README.md#getting-started), which mentions `@storybook/test-runner`. Switching to `npx` that package outputs what I assume is the correct behavior per the existing docs, e.g.: "The above should have created a file in the root directory, test-runner-jest.config.js"

## Suggested Fix

Update instructions to use storybook's package

```diff
- npx test-storybook --eject
+ npx @storybook/test-runner --eject
```

## Documentation Checklist

- [x] Typos
- [x] Grammar
- [x] Incorrect information
- [x] Missing information

**Comment by omacranger** [comment]
Hey! Thanks for pointing this out! The current guide works if the package is already installed since it's finding the `test-storybook` 'binary' installed by `@storybook/test-runner` at `/node_modules/.bin/test-storybook`. I think that's a good point though and this should be updated. Let me put a PR together.
