### ISSUE TITLE
Issue with Using Appium page

### ISSUE THREAD

**Issue by spider-sauce** [saucelabs/sauce-docs#565]
### Have you read the [Contributing Guidelines on issues?](https://github.com/saucelabs/sauce-docs/blob/master/CONTRIBUTING.MD#reporting-bugs)

- [x] Yes

## Description

There are some flow issues, inconsistencies, and inaccuracies with the `Using Appium` page. Discussion originated in #554 pull request.

__Doc URL:__ [Using Appium](https://github.com/saucelabs/sauce-docs/blob/master/docs/mobile-apps/automated-testing/appium/using-appium.md)

## Suggested Fix

Below are the links to the previous conversations:
- [General tone / fix](https://github.com/saucelabs/sauce-docs/pull/554/#pullrequestreview-716618495)
- [Add local installation steps and other info](https://github.com/saucelabs/sauce-docs/pull/554/files/29a3a1554ca90341de81eb01bd664143252618ca#r678019325)
- [Issues with doc goals and objectives](https://github.com/saucelabs/sauce-docs/pull/554/files/29a3a1554ca90341de81eb01bd664143252618ca#r678017669)
- [WebDriver Instance definition suggestion](https://github.com/saucelabs/sauce-docs/pull/554/files/29a3a1554ca90341de81eb01bd664143252618ca#r678022216)
- [Similar issue as above](https://github.com/saucelabs/sauce-docs/pull/554/files/29a3a1554ca90341de81eb01bd664143252618ca#r678023335)
- [Same as above](https://github.com/saucelabs/sauce-docs/pull/554/files/29a3a1554ca90341de81eb01bd664143252618ca#r678024175)
- [Contradicting statements with regards to `AccessibilityID`](https://github.com/saucelabs/sauce-docs/pull/554/files/29a3a1554ca90341de81eb01bd664143252618ca#r678026041)
- [Locator Strategy / Explanations could use some updates](https://github.com/saucelabs/sauce-docs/pull/554/files/29a3a1554ca90341de81eb01bd664143252618ca#r678027606)
- [Another platform / device specificity issue](https://github.com/saucelabs/sauce-docs/pull/554/files/29a3a1554ca90341de81eb01bd664143252618ca#r678028337)
- [Element locator strategy needs more explanation](https://github.com/saucelabs/sauce-docs/pull/554/files/29a3a1554ca90341de81eb01bd664143252618ca#r678028619)
- [Incorrect information regarding `submit` method](https://github.com/saucelabs/sauce-docs/pull/554/files/29a3a1554ca90341de81eb01bd664143252618ca#r678029175)
- [Missing pass/fail status](https://github.com/saucelabs/sauce-docs/pull/554/files/29a3a1554ca90341de81eb01bd664143252618ca#r678031053)
- [Potential to link to Sauce Bindings as optional strategy](https://github.com/saucelabs/sauce-docs/pull/554/files/29a3a1554ca90341de81eb01bd664143252618ca#r678031328)
- [Abrupt context switch](https://github.com/saucelabs/sauce-docs/pull/554/files/29a3a1554ca90341de81eb01bd664143252618ca#r678031561)
- [James's information architecture suggestion](https://github.com/saucelabs/sauce-docs/pull/554/files/29a3a1554ca90341de81eb01bd664143252618ca#r678538987)

## Documentation Checklist

- [ ] Typos
- [ ] Grammar
- [x] Incorrect information
- [x] Missing information

**Comment by walkerlj0** [comment]
We should also add in how to use Appium Desktop with Sauce Labs as shown in Wim's video here at ~5:30 https://www.youtube.com/watch?v=3Mnz7K9WJts&t=330s

**Comment by sweeneyskirt-sl** [comment]
I am working on it, @spider-sauce. The Appium rewrite kinda got pushed to my back burner, but I am planning to devote some focus time to it over the next week.
