### ISSUE TITLE
Make docs page a proper PWA application

### ISSUE THREAD

**Issue by christian-bromann** [saucelabs/sauce-docs#809]
### Have you read the [contributing guidelines on issues?](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md#reporting-bugs)

- [x] Yes

## Description

Our docs are currently not PWA compliant:
![Screenshot 2021-10-18 at 14 33 32](https://user-images.githubusercontent.com/731337/137731435-9e81b370-3e10-4a47-bf6b-0713fa56a0c9.png)

## Motivation

[Progressive Web Apps](https://web.dev/progressive-web-apps/) (short PWAs) are web applications that follow a certain set of best practices to improve the experience of users using the app.

> Progressive Web Apps are web applications that have been designed so they are capable, reliable, and installable. These three pillars transform them into an experience that feels like a platform-specific application.

We can't expect that only desktop users crawl through our docs. Transforming our docs into a PWA would allow users to download it and use it while offline. It would improve the performance overall and will increase the UX in general.

**Comment by lauramthomas** [comment]
@christian-bromann Thanks for the feedback! I will create a Jira ticket to look into this.

**Comment by sweeneyskirt-sl** [comment]
FYI on this one, @lauramthomas  and @spider-sauce: Docusaurus has a new PWA plugin introduced in 2.0 Beta 8: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-pwa Not sure whether this would be helpful in researching this issue.

**Comment by maxdobeck** [comment]
Can be re-opened later, but not a priority at the moment.
