### ISSUE TITLE
Sauce Connect Docs are invalid 

### ISSUE THREAD

**Issue by TroyWalshProf** [saucelabs/sauce-docs#818]
### Have you read the [Contributing Guidelines on issues?](https://github.com/saucelabs/sauce-docs/blob/main/docs/contributing.md)

- [X] Yes

## Description
Issue #768  changed the Sauce Connect documentation.
It changed how you should identify the tunnel.
So 
`caps.SetCapability("tunnelIdentifier", "TUNNEL_NAME");`
Became
`caps.SetCapability("tunnelName", "TUNNEL_NAME");`

## To Reproduce

1. Follow the step to setup and use the Sauce Connect proxy from https://docs.saucelabs.com/secure-connections/sauce-connect/setup-configuration/basic-setup/
2. Run a test against Sauce Labs using the tunnel
3. Note that the test shows an inactive tunnel ![image](https://user-images.githubusercontent.com/2066107/137935943-6a263f81-205a-4d4a-9e93-b075f260d045.png)
4. Change your Selenium code to use "tunnelIdentifier" instead of "tunnelName"
5. Note your test now uses a tunnel ![image](https://user-images.githubusercontent.com/2066107/137936569-71c34af4-eac8-475e-9eba-1069a8245895.png)

## Expected Behavior

Using the **_tunnelName_** capability would allow you to use the tunnel

## Actual Behavior

Using the _**tunnelIdentifier**_ capability would allow you to use the tunnel

## Your Environment
C# using Selenium 3.141.0

**Comment by sweeneyskirt-sl** [comment]
Thank you for bringing this to our attention, @TroyWalshProf. After checking with the development team, it seems the caps name change is only relevant for Appium RDC tests, so you are correct -- the original `tunnelIdentifier` capability is still required for Selenium tests as well as Appium EMUSIM tests. I will update the documentation to reflect this distinction and thanks!

**Comment by christian-bromann** [comment]
@sweeneyskirt-sl does this mean we have to use `tunnelName` for RDC tests and `tunnelIdentifier` for everything else?

Could we also update the SC changelogs and document changes that were introduced in `v4.7.0`?

**Comment by sweeneyskirt-sl** [comment]
Hi @christian-bromann -- My understanding is that `tunnelName` and `tunnelOwner` capabilities have only been implemented for Appium RDC and saucectl (all supported FWs). Appium EMUSIM and Selenium still require `tunnelIdentifier` and `parentTunnel`.
However, even though `tunnelIdentifier` and `parentTunnel` are deprecated for Appium RDC, they still work, so if a customer continued to use the old capabilities, their tests should run without issue.
I hope this answered your question.

**Comment by spider-sauce** [comment]
@sweeneyskirt-sl I'm going to close this out because it looks like it's fixed.
